# Generated by Django 5.0.3 on 2024-03-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0002_initial"),
        ("user", "0002_alter_user_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="posts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="social_network.post",
            ),
        ),
    ]
